version: '3'
services:
    haproxy:
        container_name: lb
        environment:
            - CERTS=garciash.duckdns.org
            - EMAIL=garcia.msn@hotmail.com
            - STAGING=true
        volumes:
            - '$PWD/data/letsencrypt:/etc/letsencrypt'
            - '$PWD/data/haproxy:/etc/haproxy'
        networks:
            - alyantNet
        ports:
            - '80:8080'
            - '443:8443'
        image: 'docker-haproxy-certbot:latest'
    rsyslog:
        container_name: rsyslog
        environment:
            - TZ=UTC
            - ENV_VAR=121333
        volumes:
            - '$PWD/data/rsyslog/config:/config'
        networks:
            - alyantNet
        ports:
            - '514:514'
        image: 'rsyslog/syslog_appliance_alpine'
    back01:
        container_name: lorem-ipsum-01
        networks:
            - alyantNet
        image: 'alyant-lorem-ipsum:latest'
    back02:
        container_name: lorem-ipsum-02
        networks:
            - alyantNet
        image: 'alyant-lorem-ipsum:latest'
    back03:
        container_name: lorem-ipsum-03
        networks:
            - alyantNet
        image: 'alyant-lorem-ipsum:latest'
networks:
    alyantNet:
        driver: bridge